apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  labels:
    app.kubernetes.io/component: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      serviceAccountName: default-service-account
      containers:
      - name: backend-api
        image: paritytech/substrate-playground-backend-api
        ports:
        - containerPort: 80
        env:
          # See https://rocket.rs/v0.4/guide/configuration/
          - name: ROCKET_ENV
            value: "staging"
          - name: ROCKET_PORT
            value: "80"
          - name: ROCKET_LOG
            value: "debug"
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: SESSION_DEFAULT_DURATION
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.defaultDuration
          - name: SESSION_MAX_DURATION
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.maxDuration
          - name: SESSION_DEFAULT_POOL_AFFINITY
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.defaultPoolAffinity
          - name: SESSION_DEFAULT_MAX_PER_NODE
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.defaultMaxPerNode
          - name: GITHUB_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: github.clientId
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: playground-secrets
                key: github.clientSecret
          - name: ROCKET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: playground-secrets
                key: rocket.secretKey
