name: Continuous Integration playground

on:
  pull_request:
    paths:
      - '.github/workflows/ci-playground.yml'
      - 'backend/**'
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn install --check-files

      - name: Lint
        run: yarn lint
        continue-on-error: true

      - name: Audit
        run: yarn audit
        continue-on-error: true

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  backend:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    steps:

      - uses: actions/checkout@v2

      # Workaround https://github.com/actions-rs/toolchain/issues/110
      - name: Make toolchain version available in current directory
        run: cp backend/rust-toolchain .

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: test
          # Workaround https://github.com/actions-rs/cargo/issues/86
          args: --manifest-path backend/Cargo.toml

  docker:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    steps:

      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build frontend Dockerfile
        run: cd frontend && docker build -f Dockerfile .

      - name: Build backend Dockerfile
        run: cd backend && docker build -f Dockerfile .
